/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import util.Calculos;

/**
 *
 * @author Gabe e Koto
 */
public class TelaFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaFuncionario
     */
    public TelaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        lblNumero2 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        btnDividir = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnOperacoes = new javax.swing.JMenu();
        itmSomar = new javax.swing.JMenuItem();
        itmMultiplicar = new javax.swing.JMenuItem();
        itmDividir = new javax.swing.JMenuItem();
        itmSubtrair = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmSair = new javax.swing.JMenuItem();
        mnBanco = new javax.swing.JMenu();
        mnAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Funcionários");
        getContentPane().setLayout(null);

        lblNumero1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumero1.setText("Número 1");
        getContentPane().add(lblNumero1);
        lblNumero1.setBounds(40, 30, 70, 20);

        txtNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumero1);
        txtNumero1.setBounds(140, 30, 100, 30);

        lblNumero2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNumero2.setText("Número 2");
        getContentPane().add(lblNumero2);
        lblNumero2.setBounds(40, 80, 70, 20);
        getContentPane().add(txtNumero2);
        txtNumero2.setBounds(140, 80, 100, 30);

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDividir);
        btnDividir.setBounds(420, 160, 100, 23);

        btnSubtrair.setText("Subtrair");
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtrair);
        btnSubtrair.setBounds(300, 160, 90, 23);

        btnSomar.setText("Somar");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomar);
        btnSomar.setBounds(50, 160, 90, 23);

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar);
        btnMultiplicar.setBounds(170, 160, 100, 23);

        lblResultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(320, 60, 70, 20);

        txtResultado.setEditable(false);
        txtResultado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtResultado);
        txtResultado.setBounds(400, 60, 100, 30);

        mnOperacoes.setMnemonic('O');
        mnOperacoes.setText("Operações");

        itmSomar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSomar.setMnemonic('S');
        itmSomar.setText("Somar");
        itmSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSomarActionPerformed(evt);
            }
        });
        mnOperacoes.add(itmSomar);

        itmMultiplicar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmMultiplicar.setMnemonic('M');
        itmMultiplicar.setText("Multiplicar");
        mnOperacoes.add(itmMultiplicar);

        itmDividir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmDividir.setMnemonic('V');
        itmDividir.setText("Dividir");
        mnOperacoes.add(itmDividir);

        itmSubtrair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSubtrair.setMnemonic('T');
        itmSubtrair.setText("Subtrair");
        mnOperacoes.add(itmSubtrair);
        mnOperacoes.add(jSeparator1);

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmSair.setMnemonic('R');
        itmSair.setText("Sair");
        mnOperacoes.add(itmSair);

        jMenuBar1.add(mnOperacoes);

        mnBanco.setMnemonic('B');
        mnBanco.setText("Banco de Dados");
        jMenuBar1.add(mnBanco);

        mnAjuda.setMnemonic('A');
        mnAjuda.setText("Ajuda");
        jMenuBar1.add(mnAjuda);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(615, 318));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSomarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmSomarActionPerformed

    private void txtNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1ActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        double resultado;
        resultado = Calculos.somar(Double.parseDouble(txtNumero1.getText()), Double.parseDouble(txtNumero2.getText()));
        txtResultado.setText(String.valueOf(resultado));        
        
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        double resultado;
        resultado = Calculos.multiplicar(Double.parseDouble(txtNumero1.getText()), Double.parseDouble(txtNumero2.getText()));
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        double resultado;
        resultado = Calculos.subtrair(Double.parseDouble(txtNumero1.getText()), Double.parseDouble(txtNumero2.getText()));
        txtResultado.setText(String.valueOf(resultado));        
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        double resultado;
        resultado = Calculos.dividir(Double.parseDouble(txtNumero1.getText()), Double.parseDouble(txtNumero2.getText()));
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnDividirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JMenuItem itmDividir;
    private javax.swing.JMenuItem itmMultiplicar;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmSomar;
    private javax.swing.JMenuItem itmSubtrair;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JMenu mnAjuda;
    private javax.swing.JMenu mnBanco;
    private javax.swing.JMenu mnOperacoes;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
